# Generated by Django 5.0.3 on 2024-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentnotification',
            old_name='original_tx_id',
            new_name='brandId',
        ),
        migrations.RenameField(
            model_name='paymentnotification',
            old_name='acquirer_tx_id',
            new_name='merchantTxId',
        ),
        migrations.RenameField(
            model_name='paymentnotification',
            old_name='brand_id',
            new_name='txId',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='acquirer_amount',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='acquirer_currency',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='language',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='merchant_tx_id',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='myriad_flow_id',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='payment_solution_id',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='tx_id',
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='acquirerAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='acquirerCurrency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='customerId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='merchantId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='paymentSolutionId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='acquirer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='action',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='auth_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
