# Generated by Django 5.0.3 on 2024-04-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notification'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotification',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.simpleorder'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
