# Generated by Django 5.0.3 on 2024-04-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Test', max_length=100, verbose_name='Customer Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
