# Generated by Django 5.0.3 on 2024-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleorder',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=188.0, max_digits=10, verbose_name='Total Price'),
            preserve_default=False,
        ),
    ]
